name: bbm
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: 1.0.0

  cupertino_icons: ^0.1.0
  flutter_staggered_grid_view: "^0.2.7"
  font_awesome_flutter: "^8.0.0"

dev_dependencies:
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  - assets/images/redan.jpg
  - assets/images/microphone.png
  - assets/images/wallet.png
  - assets/images/joystick.png
  - assets/icon/icon.png

  fonts:
  - family: Themify
    fonts:
    - asset: assets/fonts/themify.ttf
  - family: LineAwesome
    fonts:
    - asset: assets/fonts/line-awesome.ttf
  - family: Timeburner
    fonts:
    - asset: assets/fonts/timeburnernormal.ttf
    - asset: assets/fonts/timeburnerbold.ttf
      weight: 700
